name: vapp
description: The event app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  google_sign_in: ^4.0.1
  flutter_facebook_login: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  http: ^0.12.0


dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: #ffffffff
  android: "launcher_icon"
  ios: true
  image_path: "res/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cera-Pro
      fonts:
        - asset: res/fonts/Cera-Pro-Regular.otf
        - asset: res/fonts/Cera-Pro-Regular-Italic.otf
          style: italic
        - asset: res/fonts/Cera-Pro-Bold.otf
          weight: 700
        - asset: res/fonts/Cera-Pro-Bold-Italic.otf
          weight: 700
          style: italic
    - family:  SocialIcons
      fonts:
        - asset: res/fonts/SocialIcons.ttf
