/// Flutter icons SocialIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialIcons
///      fonts:
///       - asset: fonts/SocialIcons.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialIcons';

  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData google_plus_circle = const IconData(0xf2b3, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xf30a, fontFamily: _kFontFam);
}
